name: AndroidBuild Pipeline
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the action on'
        required: true
        default: 'master'
      action:
        description: 'Select the action to run'
        required: true
        default: 'build'
        options:
          - build
          - test
          - deploy
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Create local.properties file
      - name: Create local.properties file
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> local.properties  

      # Build the APK
      - name: Build APK
        run: ./gradlew assembleDebug

      # Optional: Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk