name: Android CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Grant execute permission for gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Run linting
      - name: Run Lint
        run: ./gradlew lintDebug

      # Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Build the APK
      - name: Build APK
        run: ./gradlew assembleDebug

      # Optional: Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk