name: Android CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Grant execute permission for gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Create local.properties file
      - name: Create local.properties file
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> local.properties

      # Run linting
      - name: Run Lint
        run: ./gradlew lintDebug

  test:
    runs-on: ubuntu-latest
    needs: build  # Depends on the 'build' job

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Create local.properties file dynamically
      - name: Create local.properties file
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" > local.properties
          echo "sdk.dir=$ANDROID_HOME" >> local.properties

      # Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

  assemble:
    runs-on: ubuntu-latest
    needs: test  # Depends on the 'test' job

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build the APK
      - name: Build APK
        run: ./gradlew assembleDebug

      # Optional: Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk